version: '3.7'

services:
  super-bot:
    image: gfaraj/super-bot:latest
    build: .
    env_file: 
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    ports:
      - "3000:3000"
    command: npm run start:mon